"""Reusable terminal UI components for TriCore."""

from .terminal import (
    COLOR_EXPLANATION,
    COLOR_ERROR,
    COLOR_NORMAL,
    COLOR_RESULT,
    COLOR_TITLE,
    box,
    error_screen,
    explanation_screen,
    help_screen,
    input_screen,
    key_value_lines,
    menu_screen,
    pause,
    print_screen,
    prompt,
    result_screen,
    section,
    success_message,
    table_lines,
)

__all__ = [
    "COLOR_EXPLANATION",
    "COLOR_ERROR",
    "COLOR_NORMAL",
    "COLOR_RESULT",
    "COLOR_TITLE",
    "box",
    "error_screen",
    "explanation_screen",
    "help_screen",
    "input_screen",
    "key_value_lines",
    "menu_screen",
    "pause",
    "print_screen",
    "prompt",
    "result_screen",
    "section",
    "success_message",
    "table_lines",
]
